pragma Singleton

import Quickshell
import Quickshell.Io
import QtQuick
import "../components/theme"

Singleton {
    id: root

    readonly property string homeDirectory: Quickshell.env("HOME")
    readonly property string dataHome: Quickshell.env("XDG_DATA_HOME")
        || homeDirectory + "/.local/share"
    readonly property string themeRoot: dataHome + "/themes"
    readonly property url templatePath: Qt.resolvedUrl("../gtk-theme.css")
    property bool directoriesPrepared: false
    property bool alternateThemeName: false
    signal preparationCompleted()

    function colorToHex(colorValue): string {
        const channel = value => Math.round(value * 255).toString(16).padStart(2, "0");
        return "#" + channel(colorValue.r) + channel(colorValue.g)
            + channel(colorValue.b);
    }

    function mixColors(first, second, amount): color {
        return Qt.rgba(
            first.r + (second.r - first.r) * amount,
            first.g + (second.g - first.g) * amount,
            first.b + (second.b - first.b) * amount,
            1
        );
    }

    function darkSurfaceColor(): color {
        const base = Theme.shellBackgroundColor;
        const hue = base.hslHue >= 0 ? base.hslHue : 0;
        return Qt.hsla(hue, Math.max(0.24,
            Math.min(0.82, base.hslSaturation)), 0.035, 1);
    }

    function yellowColor(): color {
        const blended = mixColors("#f9e2af", Theme.accentColor, 0.22);
        const hue = blended.hslHue >= 0 ? blended.hslHue : 0;
        return Qt.hsla(hue, Math.max(0.48,
            Math.min(0.82, blended.hslSaturation)), 0.70, 1);
    }

    function renderGtkStylesheet(): string {
        const replacements = {
            "@BACKGROUND@": colorToHex(Theme.shellBackgroundColor),
            "@SURFACE@": colorToHex(Theme.panelSurfaceColor),
            "@SURFACE_DARK@": colorToHex(darkSurfaceColor()),
            "@BORDER@": colorToHex(Theme.surfaceBorderColor),
            "@FOREGROUND@": colorToHex(Theme.primaryTextColor),
            "@MUTED@": colorToHex(Theme.secondaryTextColor),
            "@ACCENT@": colorToHex(Theme.accentColor),
            "@SELECTION@": colorToHex(Theme.selectedSurfaceColor),
            "@RED@": colorToHex(Theme.dangerColor),
            "@GREEN@": colorToHex(Theme.successColor),
            "@YELLOW@": colorToHex(yellowColor())
        };
        let output = templateFile.text();
        for (const token in replacements)
            output = output.split(token).join(replacements[token]);
        return "/* Generated by Quickshell. Do not edit. */\n" + output;
    }

    function renderThemeIndex(themeName): string {
        return "[Desktop Entry]\n"
            + "Type=X-GNOME-Metatheme\n"
            + "Name=" + themeName + "\n"
            + "Comment=Wallpaper-derived Quickshell GTK theme\n"
            + "Encoding=UTF-8\n\n"
            + "[X-GNOME-Metatheme]\n"
            + "GtkTheme=" + themeName + "\n";
    }

    function prepareThemeDirectories(): void {
        if (!directoriesPrepared && !directoryPreparation.running)
            directoryPreparation.running = true;
    }

    function exportGtkTheme(): void {
        if (!directoriesPrepared)
            return;

        alternateThemeName = !alternateThemeName;
        // Alternating names makes GTK observe a setting change and reload the rewritten CSS.
        const themeName = alternateThemeName
            ? "QuickshellDynamicOne" : "QuickshellDynamicTwo";
        const themePath = themeRoot + "/" + themeName;
        const stylesheet = renderGtkStylesheet();

        themeIndexFile.path = themePath + "/index.theme";
        gtk3ThemeFile.path = themePath + "/gtk-3.0/gtk.css";
        gtk4ThemeFile.path = themePath + "/gtk-4.0/gtk.css";
        themeIndexFile.setText(renderThemeIndex(themeName));
        gtk3ThemeFile.setText(stylesheet);
        gtk4ThemeFile.setText(stylesheet);

        gtkReload.command = ["dconf", "write",
            "/org/gnome/desktop/interface/gtk-theme", "'" + themeName + "'"];
        gtkReload.running = true;
    }

    FileView {
        id: templateFile
        path: root.templatePath
        blockLoading: true
        printErrors: true
    }

    FileView {
        id: themeIndexFile
        atomicWrites: true
        printErrors: false
    }

    FileView {
        id: gtk3ThemeFile
        atomicWrites: true
        printErrors: false
    }

    FileView {
        id: gtk4ThemeFile
        atomicWrites: true
        printErrors: false
    }

    Process { id: gtkReload }

    Process {
        id: directoryPreparation
        command: ["mkdir", "-p",
            root.themeRoot + "/QuickshellDynamicOne/gtk-3.0",
            root.themeRoot + "/QuickshellDynamicOne/gtk-4.0",
            root.themeRoot + "/QuickshellDynamicTwo/gtk-3.0",
            root.themeRoot + "/QuickshellDynamicTwo/gtk-4.0"]
        onExited: exitCode => {
            if (exitCode !== 0)
                return;
            root.directoriesPrepared = true;
            root.preparationCompleted();
        }
    }
}
