pragma Singleton

import Quickshell
import Quickshell.Io
import QtQuick
import "../components"

Singleton {
    id: root

    readonly property QtObject dynamic: Theme.dynamic
    readonly property string kittyPath: "/home/mystiafin/.config/quickshell/terminal-colors-kitty.conf"
    readonly property string footPath: "/home/mystiafin/.config/quickshell/terminal-colors-foot.ini"
    readonly property string configHome: Quickshell.env("XDG_CONFIG_HOME")
        || Quickshell.env("HOME") + "/.config"
    readonly property string dataHome: Quickshell.env("XDG_DATA_HOME")
        || Quickshell.env("HOME") + "/.local/share"
    readonly property string themeRoot: dataHome + "/themes"
    readonly property string gtkTemplatePath: Qt.resolvedUrl("../gtk-theme.css")
    property bool gtkPrepared: false
    property bool gtkVariant: false

    function hex(colorValue, prefix): string {
        const channel = value => Math.round(value * 255).toString(16).padStart(2, "0");
        return (prefix ? "#" : "") + channel(colorValue.r)
            + channel(colorValue.g) + channel(colorValue.b);
    }

    function terminalColors(): var {
        const background = dynamic.foregroundColor;
        const foreground = dynamic.textColor;
        const black = dynamic.searchBackgroundColor;
        const yellow = dynamic.harmonize("#f9e2af", dynamic.accentColor, 0.22);
        const magenta = dynamic.harmonize("#f5c2e7", dynamic.accentColor, 0.28);
        const cyan = dynamic.harmonize("#94e2d5", dynamic.accentColor, 0.24);
        const regular = colorValue => dynamic.tone(colorValue, 0.58, 0.44);

        return {
            background: background,
            foreground: foreground,
            selectionBackground: dynamic.highlightColor,
            selectionForeground: foreground,
            cursor: dynamic.accentColor,
            colors: [
                black,
                regular(dynamic.redColor),
                regular(dynamic.greenColor),
                regular(yellow),
                regular(dynamic.blueColor),
                regular(magenta),
                regular(cyan),
                dynamic.secondaryTextColor,
                dynamic.placeholderTextColor,
                dynamic.redColor,
                dynamic.greenColor,
                yellow,
                dynamic.blueColor,
                magenta,
                cyan,
                foreground
            ]
        };
    }

    function kittyConfig(colors): string {
        let output = "# Generated by Quickshell. Do not edit.\n";
        output += "background " + hex(colors.background, true) + "\n";
        output += "foreground " + hex(colors.foreground, true) + "\n";
        output += "cursor " + hex(colors.cursor, true) + "\n";
        output += "cursor_text_color " + hex(colors.background, true) + "\n";
        output += "selection_background " + hex(colors.selectionBackground, true) + "\n";
        output += "selection_foreground " + hex(colors.selectionForeground, true) + "\n";
        output += "active_border_color " + hex(colors.cursor, true) + "\n";
        output += "active_tab_background " + hex(colors.cursor, true) + "\n";
        output += "active_tab_foreground " + hex(colors.background, true) + "\n";
        output += "inactive_tab_background " + hex(colors.colors[0], true) + "\n";
        output += "inactive_tab_foreground " + hex(colors.colors[8], true) + "\n";
        output += "tab_bar_background " + hex(colors.colors[0], true) + "\n";
        for (let index = 0; index < colors.colors.length; index++)
            output += "color" + index + " " + hex(colors.colors[index], true) + "\n";
        return output;
    }

    function footConfig(colors): string {
        let output = "# Generated by Quickshell. Do not edit.\n[colors-dark]\n";
        output += "alpha=0.92\n";
        output += "background=" + hex(colors.background, false) + "\n";
        output += "foreground=" + hex(colors.foreground, false) + "\n";
        output += "selection-background=" + hex(colors.selectionBackground, false) + "\n";
        output += "selection-foreground=" + hex(colors.selectionForeground, false) + "\n";
        output += "cursor=" + hex(colors.background, false) + " " + hex(colors.cursor, false) + "\n";
        output += "urls=" + hex(dynamic.blueColor, false) + "\n";
        for (let index = 0; index < 8; index++)
            output += "regular" + index + "=" + hex(colors.colors[index], false) + "\n";
        for (let index = 0; index < 8; index++)
            output += "bright" + index + "=" + hex(colors.colors[index + 8], false) + "\n";
        return output;
    }

    function gtkConfig(colors): string {
        const replacements = {
            "@BACKGROUND@": hex(colors.background, true),
            "@SURFACE@": hex(dynamic.searchBackgroundColor, true),
            "@SURFACE_DARK@": hex(dynamic.tone(dynamic.baseColor, 0.035, 0.24), true),
            "@BORDER@": hex(dynamic.searchBorderColor, true),
            "@FOREGROUND@": hex(colors.foreground, true),
            "@MUTED@": hex(dynamic.secondaryTextColor, true),
            "@ACCENT@": hex(dynamic.accentColor, true),
            "@SELECTION@": hex(dynamic.highlightColor, true),
            "@RED@": hex(dynamic.redColor, true),
            "@GREEN@": hex(dynamic.greenColor, true),
            "@YELLOW@": hex(dynamic.harmonize("#f9e2af", dynamic.accentColor, 0.22), true)
        };
        let output = gtkTemplateFile.text();
        for (const token in replacements)
            output = output.split(token).join(replacements[token]);
        return "/* Generated by Quickshell. Do not edit. */\n" + output;
    }

    function gtkIndex(themeName): string {
        return "[Desktop Entry]\n"
            + "Type=X-GNOME-Metatheme\n"
            + "Name=" + themeName + "\n"
            + "Comment=Wallpaper-derived Quickshell GTK theme\n"
            + "Encoding=UTF-8\n\n"
            + "[X-GNOME-Metatheme]\n"
            + "GtkTheme=" + themeName + "\n";
    }

    function exportGtk(colors): void {
        if (!root.gtkPrepared)
            return;

        root.gtkVariant = !root.gtkVariant;
        const themeName = root.gtkVariant
            ? "QuickshellDynamicOne" : "QuickshellDynamicTwo";
        const themePath = root.themeRoot + "/" + themeName;
        const css = root.gtkConfig(colors);

        gtkThemeIndexFile.path = themePath + "/index.theme";
        gtk3ThemeFile.path = themePath + "/gtk-3.0/gtk.css";
        gtk4ThemeFile.path = themePath + "/gtk-4.0/gtk.css";
        gtkThemeIndexFile.setText(root.gtkIndex(themeName));
        gtk3ThemeFile.setText(css);
        gtk4ThemeFile.setText(css);
        gtk3UserFile.setText(css);
        gtk4UserFile.setText(css);

        gtkReload.command = ["gsettings", "set",
            "org.gnome.desktop.interface", "gtk-theme", themeName];
        gtkReload.running = true;
    }

    function exportTheme(): void {
        const colors = terminalColors();
        kittyFile.setText(kittyConfig(colors));
        footFile.setText(footConfig(colors));
        root.exportGtk(colors);

        kittyReload.command = ["kitty", "@", "--to", "unix:@quickshell-kitty",
            "set-colors", "--all", "--configured", kittyPath];
        kittyReload.running = true;
    }

    FileView {
        id: kittyFile
        path: root.kittyPath
        atomicWrites: true
        printErrors: true
    }

    FileView {
        id: footFile
        path: root.footPath
        atomicWrites: true
        printErrors: true
    }

    FileView {
        id: gtkTemplateFile
        path: root.gtkTemplatePath
        blockLoading: true
        printErrors: true
    }

    FileView {
        id: gtkThemeIndexFile
        atomicWrites: true
        printErrors: false
    }

    FileView {
        id: gtk3ThemeFile
        atomicWrites: true
        printErrors: false
    }

    FileView {
        id: gtk4ThemeFile
        atomicWrites: true
        printErrors: false
    }

    FileView {
        id: gtk3UserFile
        path: root.configHome + "/gtk-3.0/gtk.css"
        atomicWrites: true
        printErrors: false
    }

    FileView {
        id: gtk4UserFile
        path: root.configHome + "/gtk-4.0/gtk.css"
        atomicWrites: true
        printErrors: false
    }

    Process { id: kittyReload }
    Process { id: gtkReload }

    Process {
        id: gtkPrepare
        command: ["mkdir", "-p",
            root.configHome + "/gtk-3.0",
            root.configHome + "/gtk-4.0",
            root.themeRoot + "/QuickshellDynamicOne/gtk-3.0",
            root.themeRoot + "/QuickshellDynamicOne/gtk-4.0",
            root.themeRoot + "/QuickshellDynamicTwo/gtk-3.0",
            root.themeRoot + "/QuickshellDynamicTwo/gtk-4.0"]
        onExited: {
            root.gtkPrepared = true;
            exportTimer.restart();
        }
    }

    Timer {
        id: exportTimer
        interval: 100
        onTriggered: root.exportTheme()
    }

    Connections {
        target: root.dynamic
        function onPaletteChanged(): void { exportTimer.restart(); }
    }

    Component.onCompleted: gtkPrepare.running = true
}
