pragma Singleton

import Quickshell
import Quickshell.Io
import QtQuick
import "../components"

Singleton {
    id: root

    readonly property QtObject dynamic: Theme.dynamic
    readonly property string kittyPath: "/home/mystiafin/.config/quickshell/terminal-colors-kitty.conf"
    readonly property string footPath: "/home/mystiafin/.config/quickshell/terminal-colors-foot.ini"
    readonly property string gtkPath: "/home/mystiafin/.config/quickshell/gtk-dynamic.css"
    readonly property string gtkBasePath: "/home/mystiafin/.config/quickshell/gtk-base.css"
    property bool gtkVariant: false

    function hex(colorValue, prefix): string {
        const channel = value => Math.round(value * 255).toString(16).padStart(2, "0");
        return (prefix ? "#" : "") + channel(colorValue.r)
            + channel(colorValue.g) + channel(colorValue.b);
    }

    function terminalColors(): var {
        const background = dynamic.foregroundColor;
        const foreground = dynamic.textColor;
        const black = dynamic.searchBackgroundColor;
        const yellow = dynamic.harmonize("#f9e2af", dynamic.accentColor, 0.22);
        const magenta = dynamic.harmonize("#f5c2e7", dynamic.accentColor, 0.28);
        const cyan = dynamic.harmonize("#94e2d5", dynamic.accentColor, 0.24);
        const regular = colorValue => dynamic.tone(colorValue, 0.58, 0.44);

        return {
            background: background,
            foreground: foreground,
            selectionBackground: dynamic.highlightColor,
            selectionForeground: foreground,
            cursor: dynamic.accentColor,
            colors: [
                black,
                regular(dynamic.redColor),
                regular(dynamic.greenColor),
                regular(yellow),
                regular(dynamic.blueColor),
                regular(magenta),
                regular(cyan),
                dynamic.secondaryTextColor,
                dynamic.placeholderTextColor,
                dynamic.redColor,
                dynamic.greenColor,
                yellow,
                dynamic.blueColor,
                magenta,
                cyan,
                foreground
            ]
        };
    }

    function kittyConfig(colors): string {
        let output = "# Generated by Quickshell. Do not edit.\n";
        output += "background " + hex(colors.background, true) + "\n";
        output += "foreground " + hex(colors.foreground, true) + "\n";
        output += "cursor " + hex(colors.cursor, true) + "\n";
        output += "cursor_text_color " + hex(colors.background, true) + "\n";
        output += "selection_background " + hex(colors.selectionBackground, true) + "\n";
        output += "selection_foreground " + hex(colors.selectionForeground, true) + "\n";
        output += "active_border_color " + hex(colors.cursor, true) + "\n";
        output += "active_tab_background " + hex(colors.cursor, true) + "\n";
        output += "active_tab_foreground " + hex(colors.background, true) + "\n";
        output += "inactive_tab_background " + hex(colors.colors[0], true) + "\n";
        output += "inactive_tab_foreground " + hex(colors.colors[8], true) + "\n";
        output += "tab_bar_background " + hex(colors.colors[0], true) + "\n";
        for (let index = 0; index < colors.colors.length; index++)
            output += "color" + index + " " + hex(colors.colors[index], true) + "\n";
        return output;
    }

    function footConfig(colors): string {
        let output = "# Generated by Quickshell. Do not edit.\n[colors-dark]\n";
        output += "alpha=0.92\n";
        output += "background=" + hex(colors.background, false) + "\n";
        output += "foreground=" + hex(colors.foreground, false) + "\n";
        output += "selection-background=" + hex(colors.selectionBackground, false) + "\n";
        output += "selection-foreground=" + hex(colors.selectionForeground, false) + "\n";
        output += "cursor=" + hex(colors.background, false) + " " + hex(colors.cursor, false) + "\n";
        output += "urls=" + hex(dynamic.blueColor, false) + "\n";
        for (let index = 0; index < 8; index++)
            output += "regular" + index + "=" + hex(colors.colors[index], false) + "\n";
        for (let index = 0; index < 8; index++)
            output += "bright" + index + "=" + hex(colors.colors[index + 8], false) + "\n";
        return output;
    }

    function gtkConfig(colors): string {
        const background = hex(colors.background, true);
        const surface = hex(dynamic.searchBackgroundColor, true);
        const border = hex(dynamic.searchBorderColor, true);
        const foreground = hex(colors.foreground, true);
        const muted = hex(dynamic.secondaryTextColor, true);
        const accent = hex(dynamic.accentColor, true);
        const selection = hex(dynamic.highlightColor, true);
        const red = hex(dynamic.redColor, true);
        const green = hex(dynamic.greenColor, true);
        const yellow = hex(dynamic.harmonize("#f9e2af", dynamic.accentColor, 0.22), true);
        const magenta = hex(dynamic.harmonize("#f5c2e7", dynamic.accentColor, 0.28), true);
        const cyan = hex(dynamic.harmonize("#94e2d5", dynamic.accentColor, 0.24), true);
        const replacements = [
            ["#eff1f5", foreground], ["#1e1e2e", background],
            ["#181825", surface], ["#11111b", hex(dynamic.tone(dynamic.baseColor, 0.035, 0.24), true)],
            ["#313244", border], ["#393947", border], ["#282938", surface],
            ["#444556", border], ["#89b4fa", accent], ["#f38ba8", red],
            ["#f9e2af", yellow], ["#a6e3a1", green], ["#cba6f7", magenta],
            ["#89dceb", cyan], ["rgba(239, 241, 245,", rgbaPrefix(colors.foreground)],
            ["rgba(137, 180, 250,", rgbaPrefix(dynamic.accentColor)]
        ];
        let output = gtkBaseFile.text();
        for (let index = 0; index < replacements.length; index++)
            output = output.split(replacements[index][0]).join(replacements[index][1]);
        output = output.split('url("assets/').join(
            'url("file:///home/mystiafin/.config/quickshell/gtk-assets/');
        return "/* Recolored by Quickshell. Do not edit. */\n" + output;
    }

    function rgbaPrefix(colorValue): string {
        return "rgba(" + Math.round(colorValue.r * 255) + ", "
            + Math.round(colorValue.g * 255) + ", "
            + Math.round(colorValue.b * 255) + ",";
    }

    function exportTheme(): void {
        const colors = terminalColors();
        kittyFile.setText(kittyConfig(colors));
        footFile.setText(footConfig(colors));
        gtkFile.setText(gtkConfig(colors));

        kittyReload.command = ["kitty", "@", "--to", "unix:@quickshell-kitty",
            "set-colors", "--all", "--configured", kittyPath];
        kittyReload.running = true;

        gtkVariant = !gtkVariant;
        gtkReload.command = ["quickshell-gtk-theme",
            gtkVariant ? "QuickshellDynamicA" : "QuickshellDynamicB"];
        gtkReload.running = true;
    }

    FileView {
        id: kittyFile
        path: root.kittyPath
        atomicWrites: true
        printErrors: true
    }

    FileView {
        id: footFile
        path: root.footPath
        atomicWrites: true
        printErrors: true
    }

    FileView {
        id: gtkFile
        path: root.gtkPath
        atomicWrites: true
        printErrors: true
    }

    FileView {
        id: gtkBaseFile
        path: root.gtkBasePath
        blockLoading: true
        printErrors: true
    }

    Process { id: kittyReload }
    Process { id: gtkReload }

    Timer {
        id: exportTimer
        interval: 100
        onTriggered: root.exportTheme()
    }

    Connections {
        target: root.dynamic
        function onPaletteChanged(): void { exportTimer.restart(); }
    }

    Component.onCompleted: exportTimer.restart()
}
